version: '3'
services:
  spark-master:
    image: bde2020/spark-master:3.0.1-hadoop3.2
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - INIT_DAEMON_STEP=setup_spark
    volumes:
      - ./data:/data
    networks:
      - eventbackup

  spark-worker-1:
    image: bde2020/spark-worker:3.0.1-hadoop3.2
    container_name: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    volumes:
      - ./data:/data
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - "SPARK_WORKER_CORES=1"
      - "SPARK_WORKER_MEMORY=1024m"
    networks:
      - eventbackup

  spark-worker-2:
    image: bde2020/spark-worker:3.0.1-hadoop3.2
    container_name: spark-worker-2
    depends_on:
      - spark-master
    ports:
      - "8082:8082"
    volumes:
      - ./data:/data
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - "SPARK_WORKER_CORES=1"
      - "SPARK_WORKER_MEMORY=1024m"
    networks:
      - eventbackup

  spark-worker-3:
    image: bde2020/spark-worker:3.0.1-hadoop3.2
    container_name: spark-worker-3
    depends_on:
      - spark-master
    ports:
      - "8084:8084"
    volumes:
      - ./data:/data
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - "SPARK_WORKER_CORES=1"
      - "SPARK_WORKER_MEMORY=1024m"
    networks:
      - eventbackup

  jupyter:
    image: jupyter/all-spark-notebook
    command: jupyter notebook --NotebookApp.token='c33a7dc0eece'
    working_dir: /data
    hostname: jupyter
    environment:
      SPARK_OPTS: "--master=spark://spark-master:7077 --conf spark.ui.port=4041"
      SPARK_PUBLIC_DNS: localhost
      SPARK_EXECUTOR_CORES: 1
      SPARK_EXECUTOR_MEMORY: 512m
      SPARK_MASTER: "spark://spark-master:7077"
    links:
      - spark-master
    ports:
      - 8888:8888
      - 4041:4041
    volumes:
      - ./data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    networks:
      - eventbackup

networks:
  eventbackup: